### ISSUE TITLE
Trimmer Mantle Changes (HorizonXI)

### ISSUE THREAD

**Issue by nicholasgtan** [m4thmatic/PetMe#5]
Thanks for your work on PetMe!

HorizonXI devs recently changed trimmer mantle to increase charm duration, so using this item during charm actually extends the duration. Petme duration doesn't take into account this new change so the timer continues to run after reaching 0 and goes back to -1:59:59 and counts down for the extra time.

> From HorizonXI 1/26/2024 Patch Notes
- Trimmer's Mantle now correctly gives a charm duration increase rather than a charm rate increase (similar to other gear with +charm). (Tracent)

**Comment by m4thmatic** [comment]
Thanks, I missed that. If you happen to know/have tested how much +charm the Trimmer's Mantle gives please let me know, otherwise I'll do some testing in the next few days. I probably won't add a specific option for it (at least until I make calculating +charm automatically), but would be inclined to add a note to the readme with the amount to add.

**Comment by plastiqu3** [comment]
Trimmer Mantle on Horizon gives "Charm" +5 when BST is sub-job. Believe it uses the same formula for "Charm" + as with BST AF gear. 

Source: https://www.bg-wiki.com/ffxi/Charm_Duration#Charm+_equipment

Every +1 Charm from gear adds 5% Charm duration. This bonus is applied separately from the dLevel bonus/penalty.

Charm Duration = Pre-gear Charm Duration × ( 1 + 0.05×(Charm+ in gear) )

**Comment by m4thmatic** [comment]
Yeah, so in that case, in the settings menu (type /pm) add 5 under the charm field and it should calculate the charm duration accurately.

**Comment by plastiqu3** [comment]
ah, apologies, i just re-read the notes and saw that it's not automated. Thanks!
